### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by YuchenLi01** [IBM/Text-to-LogicForm#3]
When I ran `data_creator.py`, the following error occurred:

```
Traceback (most recent call last):
  File "data_creator.py", line 123, in <module>
    create_random_graph("no-cycle", "data/no_cycle/train2.data", 1000, graph_scale=100)
  File "data_creator.py", line 60, in create_random_graph
    for id in graph.edge:
AttributeError: 'DiGraph' object has no attribute 'edge'
```

Instead of the attribute 'edge', did you mean the attribute 'edges' instead?

**Comment by Tanjie1102** [comment]
it seems that there is a typo error.DiGraph.edge should be changed into DiGraoh.edges.
